### ISSUE TITLE
How to compile for saturn on windows?

### ISSUE THREAD

**Issue by Rizilla-OG** [vbt1/wolf4sdl#1]
Could someone point me in the right direction. I would like to compile with my steam copy data files to have all the episodes.

Any quick how-to's available?

**Comment by vbt1** [comment]
do you mean all episodes on saturn ?
check here : http://www.rockin-b.de/windows-saturnorbit.html
and here : https://segaxtreme.net/forums/saturn-dev.34/

**Comment by Rizilla-OG** [comment]
Thanks will try to compile tonight!
