### ISSUE TITLE
Sound working?

### ISSUE THREAD

**Issue by mxlgv** [vbt1/wolf4sdl#2]
Hello, I'm also porting the game, but only for KolibriOS (we also don't have sdl-mixer).  Can you share how you made the sound without it?

**Comment by vbt1** [comment]
yes sound is working, most part is in id_sd.cpp
i've converted soundfx to pcm and about music i simply play audio tracks

**Comment by mxlgv** [comment]
Cool!  It seemed too complicated to me.  I tried to use parts of the code from sdl_mixer.  Perhaps something will work out.

**Comment by vbt1** [comment]
it wasn't so hard to implement, pcm number is pcm filename

**Comment by mxlgv** [comment]
Probably your method is faster, since I still managed to assemble it with pieces from sdl_mixer and the game began to run slower
