### ISSUE TITLE
I need your advice!

### ISSUE THREAD

**Issue by mxlgv** [vbt1/wolf4sdl#3]
Hello. I am the person who, like you, ported Wolf4SDL but to the KolibriOS platform. But I noticed some kind of brakes and jumps in FPS. However, other games like SDLQUAKE run smoothly. Have you faced a similar problem?

**Comment by vbt1** [comment]
i took some parts of embedded wolf to reduce/remove brakes and jumps in FPS

**Comment by vbt1** [comment]
i've took some parts of embedded wolf to improve  FPS

**Comment by vbt1** [comment]
embedded wolf4sdl is the right choice

**Comment by mxlgv** [comment]
By the way, I solved the problem.  There was a bug in SDL_Delay in the SDL port for KolibriOS.  Sorry...
